[package]
name = "delphea-cli-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rusqlite = { version = "0.28.0", features = ["bundled"] }
rand = "0.8.5"